### ISSUE TITLE
error at the end of processing

### ISSUE THREAD

**Issue by phoenixwarlord** [facefusion/facefusion#101]
Everything was fine until it reaches the end of processing, and output just shows Error. Please help...

Processing: 100%|█| 160/160 [02:44<00:00,  1.03s/frame, memory_usage=03.68GB, execution_providers=['CPUExecutionProvide
[FACEFUSION.FRAME_PROCESSOR.FACE_ENHANCER] Processing
Traceback (most recent call last):
  File "J:\facefusion\env\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "J:\facefusion\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "J:\facefusion\env\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "J:\facefusion\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "J:\facefusion\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "J:\facefusion\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "J:\facefusion\env\lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
  File "J:\facefusion\code\facefusion\uis\components\output.py", line 44, in update
    conditional_process()
  File "core.py", line 203, in core.conditional_process
  File "core.py", line 169, in core.process_video
  File "J:\facefusion\code\facefusion\processors\frame\modules\face_enhancer.py", line 100, in process_video
    facefusion.processors.frame.core.process_video(None, temp_frame_paths, process_frames)
TypeError: Argument 'source_path' has incorrect type (expected str, got NoneType)

**Comment by henryruhs** [comment]
> TypeError: Argument 'source_path' has incorrect type (expected str, got NoneType)


I cannot reproduce this error - tested face enhancer on image and video without having a `source_path`.

**Comment by lyklll** [comment]
> Everything was fine until it reaches the end of processing, and output just shows Error. Please help...
> 
> Processing: 100%|█| 160/160 [02:44<00:00, 1.03s/frame, memory_usage=03.68GB, execution_providers=['CPUExecutionProvide [FACEFUSION.FRAME_PROCESSOR.FACE_ENHANCER] Processing Traceback (most recent call last): File "J:\facefusion\env\lib\site-packages\gradio\routes.py", line 488, in run_predict output = await app.get_blocks().process_api( File "J:\facefusion\env\lib\site-packages\gradio\blocks.py", line 1431, in process_api result = await self.call_function( File "J:\facefusion\env\lib\site-packages\gradio\blocks.py", line 1109, in call_function prediction = await anyio.to_thread.run_sync( File "J:\facefusion\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "J:\facefusion\env\lib\site-packages\anyio_backends_asyncio.py", line 877, in run_sync_in_worker_thread return await future File "J:\facefusion\env\lib\site-packages\anyio_backends_asyncio.py", line 807, in run result = context.run(func, *args) File "J:\facefusion\env\lib\site-packages\gradio\utils.py", line 706, in wrapper response = f(*args, **kwargs) File "J:\facefusion\code\facefusion\uis\components\output.py", line 44, in update conditional_process() File "core.py", line 203, in core.conditional_process File "core.py", line 169, in core.process_video File "J:\facefusion\code\facefusion\processors\frame\modules\face_enhancer.py", line 100, in process_video facefusion.processors.frame.core.process_video(None, temp_frame_paths, process_frames) TypeError: Argument 'source_path' has incorrect type (expected str, got NoneType)

I encountered the same issue！@
