### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by venshine** [facefusion/facefusion#123]
```
Traceback (most recent call last):
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/gradio/routes.py", line 508, in predict
    output = await route_utils.call_process_api(
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/Users/venshine/anaconda3/envs/facefusion/lib/python3.10/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "/Users/venshine/Work/WorkSpace/OpenSource/facefusion/facefusion/uis/components/output.py", line 54, in start
    limit_resources()
  File "/Users/venshine/Work/WorkSpace/OpenSource/facefusion/facefusion/core.py", line 122, in limit_resources
    resource.setrlimit(resource.RLIMIT_DATA, (memory, memory))
OverflowError: Python int too large to convert to C long
```
I ran into this exception and I still get this issue after I refreshed.

**Comment by henryruhs** [comment]
Don't play with the max-memory argument If you don't know what you are doing...
