### ISSUE TITLE
Error while installing dependencies on Arch Linux with a virtual environment

### ISSUE THREAD

**Issue by Qypol342** [facefusion/facefusion#13]
**Context**:
I am attempting to set up the `facefusion` project on my Dell laptop running Arch Linux. My system specifications are as follows:
- Laptop: Dell laptop
- CPU: Intel i7 (older generation)
- RAM: 8GB with swap
- Operating System: Arch Linux

**Steps Taken**:
1. Installed `ffmpeg` using pacman: `pacman -S ffmpeg`
2. Created a virtual environment named `myenv`
   ```bash
   virtualenv myenv
   source myenv/bin/activate
   ```
3. Installed packages using pip:
   ```bash
   pip install --no-cache-dir -r requirements.txt
   ```

**Issue**:
During the installation of the required packages, I encountered an error that prevented successful installation. Here is the error message I received:

```shell
pip install --no-cache-dir -r requirements.txt                                                                                                             ✔  myenv  

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Ignoring onnxruntime: markers 'python_version != "3.9" and sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-coreml: markers 'python_version == "3.9" and sys_platform == "darwin" and platform_machine != "arm64"' don't match your environment
Ignoring onnxruntime-silicon: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting gfpgan==1.3.8
  Downloading gfpgan-1.3.8-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 1.2 MB/s eta 0:00:00
Collecting gradio==3.40.1
  Downloading gradio-3.40.1-py3-none-any.whl (20.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.0/20.0 MB 2.5 MB/s eta 0:00:00
Collecting insightface==0.7.3
  Downloading insightface-0.7.3.tar.gz (439 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.5/439.5 kB 2.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy==1.24.3
  Downloading numpy-1.24.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 1.6 MB/s eta 0:00:00
Collecting onnx==1.14.0
  Downloading onnx-1.14.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 2.6 MB/s eta 0:00:00
Collecting onnxruntime-gpu==1.15.1
  Downloading onnxruntime_gpu-1.15.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 2.6 MB/s eta 0:00:00
Collecting opencv-python==4.8.0.74
  Downloading opencv_python-4.8.0.74-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 MB 2.3 MB/s eta 0:00:00
Collecting opennsfw2==0.10.2
  Downloading opennsfw2-0.10.2-py3-none-any.whl (12 kB)
Collecting pillow==10.0.0
  Downloading Pillow-10.0.0-cp311-cp311-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 2.6 MB/s eta 0:00:00
Collecting protobuf==4.23.4
  Downloading protobuf-4.23.4-cp37-abi3-manylinux2014_x86_64.whl (304 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.5/304.5 kB 2.8 MB/s eta 0:00:00
Collecting psutil==5.9.5
  Downloading psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 282.1/282.1 kB 2.6 MB/s eta 0:00:00
Collecting realesrgan==0.3.0
  Downloading realesrgan-0.3.0-py3-none-any.whl (26 kB)
Collecting tensorflow==2.13.0
  Downloading tensorflow-2.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.2/524.2 MB 1.7 MB/s eta 0:00:00
Collecting tqdm==4.65.0
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 10.8 MB/s eta 0:00:00
Collecting basicsr>=1.4.2
  Downloading basicsr-1.4.2.tar.gz (172 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.5/172.5 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [105 lines of output]
      /home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/__init__.py:85: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        dist.fetch_build_eggs(dist.setup_requires)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
          status = run_func(*args)
                   ^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
          return func(self, options, args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/commands/wheel.py", line 170, in run
          requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
          result = self._result = resolver.resolve(
                                  ^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
                 ^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
                 ^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
                      ^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
                                             ^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
          super().__init__(
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
          self.dist = self._prepare()
                      ^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
          dist = self._prepare_distribution()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
          local_file = unpack_url(
                       ^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
          file = get_http_url(
                 ^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
          from_path, content_type = download(link, temp_dir.path)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pip/_internal/network/download.py", line 148, in __call__
          content_file.write(chunk)
      OSError: [Errno 28] No space left on device
      Traceback (most recent call last):
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/installer.py", line 97, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/lo/App/facefusion/myenv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpjpya2r53', '--quiet', 'nvidia-cublas-cu11==11.10.3.66']' returned non-zero exit status 2.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-j0rokjfj/basicsr_6687d44989f944a1a7b489382d237466/setup.py", line 147, in <module>
          setup(
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          _install_setup_requires(attrs)
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/__init__.py", line 85, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 815, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1123, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1135, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lo/App/facefusion/myenv/lib/python3.11/site-packages/setuptools/installer.py", line 99, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/lo/App/facefusion/myenv/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpjpya2r53', '--quiet', 'nvidia-cublas-cu11==11.10.3.66']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Error Analysis**:
The error seems to be related to package installation within the virtual environment. Specifically, it reports a subprocess error and mentions a lack of space on the device.

**Expected Behavior**:
I expected the installation process to complete successfully and the required packages to be installed within the virtual environment.

**Additional Information**:
- I'm using Arch Linux, and my system has enough free disk space.
- I have ensured that the virtual environment is activated before running the installation command.
- The error message suggests the possibility of an issue with the `nvidia-cublas-cu11` package, but I'm not sure how it relates to my environment because i don't have a GPU and followed the basic guide

**Steps Tried**:
- Checked available disk space using `df -h`, and there is enough space.
- Verified that `virtualenv` and `pip` are up to date.

**Screenshots**:
![df -h](https://github.com/facefusion/facefusion/assets/37497007/ac65417c-9932-4869-b574-3a3d943dfc8d)

**Reproducibility**:
This issue is reproducible on my system every time I try to install the required packages using the given steps.

**Environment**:
- Python version: [3.11.3]
- Output of `pip list` within the virtual environment: 
pip        23.0.1
setuptools 67.4.0
wheel      0.38.4

**Note**:
I'm relatively new to Arch Linux and may not be aware of specific system configurations that could contribute to this issue. Any guidance or suggestions to resolve this issue would be greatly appreciated.

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
