### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'curl'

### ISSUE THREAD

**Issue by 4DeepThought2** [facefusion/facefusion#130]
curl is missing from both `/usr/bin` and /usr/local/bin` so this command will always fail inside the container:

```2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | ==========
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | == CUDA ==
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | ==========
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | 
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | CUDA Version 11.8.0
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | 
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | 
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | By pulling and using the container, you accept the terms and conditions of this license:
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | 
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
2023-09-26 10:26:24 facefusion-docker-facefusion-cuda-1  | 
Downloading:   0%|          | 0.00/529M [00:00<?, ?B/s]  | 
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  | Traceback (most recent call last):
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/facefusion/run.py", line 6, in <module>
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     core.run()
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/facefusion/facefusion/core.py", line 219, in run
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     if not frame_processor.pre_check():
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/facefusion/facefusion/processors/frame/modules/face_swapper.py", line 40, in pre_check
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     conditional_download(download_directory_path, [ MODEL_URL ])
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/facefusion/facefusion/utilities.py", line 190, in conditional_download
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     subprocess.Popen([ 'curl', '--create-dirs', '--silent', '--location', '--continue-at', '-', '--output', download_file_path, url ])
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     self._execute_child(args, executable, preexec_fn, close_fds,
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  |     raise child_exception_type(errno_num, err_msg, err_filename)
2023-09-26 10:26:26 facefusion-docker-facefusion-cuda-1  | FileNotFoundError: [Errno 2] No such file or directory: 'curl'```

**Comment by 4DeepThought2** [comment]
This can be fixed by adding `apt-get install curl -y` to the docker file.

**Comment by henryruhs** [comment]
Fixed via https://github.com/facefusion/facefusion-docker/commit/83be88aa02199fa1f1bde4db8d8f2fb4aa4ee04d
