### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface.app'

### ISSUE THREAD

**Issue by jing31711** [facefusion/facefusion#175]
Traceback (most recent call last):
  File "/workspaces/facefusion/run.py", line 3, in <module>
    from facefusion import core
  File "/workspaces/facefusion/facefusion/core.py", line 15, in <module>
    import facefusion.choices
  File "/workspaces/facefusion/facefusion/choices.py", line 3, in <module>
    from facefusion.typing import FaceRecognition, FaceAnalyserDirection, FaceAnalyserAge, FaceAnalyserGender, TempFrameFormat, OutputVideoEncoder
  File "/workspaces/facefusion/facefusion/typing.py", line 2, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface.app'

**Comment by jing31711** [comment]
Traceback (most recent call last):
  File "/workspaces/facefusion/run.py", line 3, in <module>
    from facefusion import core
  File "/workspaces/facefusion/facefusion/core.py", line 15, in <module>
    import facefusion.choices
  File "/workspaces/facefusion/facefusion/choices.py", line 3, in <module>
    from facefusion.typing import FaceRecognition, FaceAnalyserDirection, FaceAnalyserAge, FaceAnalyserGender, TempFrameFormat, OutputVideoEncoder
  File "/workspaces/facefusion/facefusion/typing.py", line 2, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface.app'

**Comment by henryruhs** [comment]
Wrong Python version, you just did not follow our guide: https://docs.facefusion.io/installation
