### ISSUE TITLE
ModuleNotFoundError: No module named 'inquirer'

### ISSUE THREAD

**Issue by Zyin055** [facefusion/facefusion#182]
Trying to install this extension on A1111 1.6.0 and get the following error when booting up.

Seems like it isn't installing `inquirer` properly.

```
*** Error running install.py for extension C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion.
*** Command: "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\venv\Scripts\python.exe" "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\install.py"
*** Error code: 1
*** stderr: WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
***
*** [notice] A new release of pip is available: 23.0 -> 23.3.1
*** [notice] To update, run: python.exe -m pip install --upgrade pip
*** Traceback (most recent call last):
***   File "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\install.py", line 3, in <module>
***     from facefusion import installer
***   File "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\facefusion\installer.py", line 7, in <module>
***     import inquirer
*** ModuleNotFoundError: No module named 'inquirer'
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion.
*** Command: "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\venv\Scripts\python.exe" "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\install.py"
*** Error code: 1
*** stderr: WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
*** WARNING: Ignoring invalid distribution -illow (c:\users\zyin\appdata\local\programs\python\python310\lib\site-packages)
***
*** [notice] A new release of pip is available: 23.0 -> 23.3.1
*** [notice] To update, run: python.exe -m pip install --upgrade pip
*** Traceback (most recent call last):
***   File "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\install.py", line 3, in <module>
***     from facefusion import installer
***   File "C:\Stuff\AI\SD\stable-diffusion-webui-LATEST\extensions\facefusion\facefusion\installer.py", line 7, in <module>
***     import inquirer
*** ModuleNotFoundError: No module named 'inquirer'
#######################################################################################################
```

**Comment by henryruhs** [comment]
Open an issue here: https://github.com/diffus-me/sd-webui-facefusion
