### ISSUE TITLE
ImportError: /usr/lib/libtorch_python.so: undefined symbol: PyFrame_GetLasti

### ISSUE THREAD

**Issue by ryenots** [facefusion/facefusion#250]
I am running on arch linux. After running the install.py script, I get the following error from run.py:

```
Traceback (most recent call last):
  File "/home/ryenots/Documents/git_files/facefusion/run.py", line 6, in <module>
    core.cli()
  File "/home/ryenots/Documents/git_files/facefusion/facefusion/core.py", line 84, in cli
    frame_processor_module = load_frame_processor_module(frame_processor)
  File "/home/ryenots/Documents/git_files/facefusion/facefusion/processors/frame/core.py", line 35, in load_frame_processor_module
    frame_processor_module = importlib.import_module('facefusion.processors.frame.modules.' + frame_processor)
  File "/home/ryenots/.conda/envs/roop/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ryenots/Documents/git_files/facefusion/facefusion/processors/frame/modules/frame_enhancer.py", line 5, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "/home/ryenots/.local/lib/python3.10/site-packages/basicsr/__init__.py", line 3, in <module>
    from .archs import *
  File "/home/ryenots/.local/lib/python3.10/site-packages/basicsr/archs/__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "/home/ryenots/.local/lib/python3.10/site-packages/basicsr/utils/__init__.py", line 1, in <module>
    from .color_util import bgr2ycbcr, rgb2ycbcr, rgb2ycbcr_pt, ycbcr2bgr, ycbcr2rgb
  File "/home/ryenots/.local/lib/python3.10/site-packages/basicsr/utils/color_util.py", line 2, in <module>
    import torch
  File "/home/ryenots/.conda/envs/roop/lib/python3.10/site-packages/torch/__init__.py", line 235, in <module>
    from torch._C import *  # noqa: F403
```

The issues page does not have anything related, so I thought I would create a new issue.

**Comment by henryruhs** [comment]
Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to complete the installation.
