### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by sosiai** [facefusion/facefusion#354]
face_swapper, start，error

2024-01-31 10:48:31.089476 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running CoreML_15882690048850409843_0 node. Name:'CoreMLExecutionProvider_CoreML_15882690048850409843_0_0' Status Message: Error executing model: Unable to compute the prediction using a neural network model. It can be an invalid input data or broken/unsupported model (error code: -1).
Traceback (most recent call last):
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "/Users/chris/Projects/facefusion/facefusion/uis/components/preview.py", line 145, in update_preview_image
    conditional_append_reference_faces()
  File "/Users/chris/Projects/facefusion/facefusion/core.py", line 230, in conditional_append_reference_faces
    source_face = get_average_face(source_frames)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 254, in get_average_face
    face = get_one_face(frame, position)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 239, in get_one_face
    many_faces = get_many_faces(frame)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 278, in get_many_faces
    faces = extract_faces(frame)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 109, in extract_faces
    return create_faces(frame, bbox_list, kps_list, score_list)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 191, in create_faces
    embedding, normed_embedding = calc_embedding(frame, kps)
  File "/Users/chris/Projects/facefusion/facefusion/face_analyser.py", line 211, in calc_embedding
    embedding = face_recognizer.run(None,
  File "/Users/chris/Projects/facefusion/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running CoreML_15882690048850409843_0 node. Name:'CoreMLExecutionProvider_CoreML_15882690048850409843_0_0' Status Message: Error executing model: Unable to compute the prediction using a neural network model. It can be an invalid input data or broken/unsupported model (error code: -1).

**Comment by henryruhs** [comment]
> Error executing model: Unable to compute the prediction using a neural network model. It can be an invalid input data or broken/unsupported model

Nothing I can do about it except telling you to try a different source and target file.
