### ISSUE TITLE
Frame processor face_enhancer could not be loaded

### ISSUE THREAD

**Issue by jeeveshlodhi** [facefusion/facefusion#44]
### Error

Applied providers: ['CUDAExecutionProvider', 'CPUExecutionProvider'], with options: {'CUDAExecutionProvider': {'do_copy_in_default_stream': '1', 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'device_id': '0', 'gpu_external_alloc': '0', 'enable_cuda_graph': '0', 'gpu_mem_limit': '18446744073709551615', 'gpu_external_free': '0', 'gpu_external_empty_cache': '0', 'arena_extend_strategy': 'kNextPowerOfTwo', 'cudnn_conv_use_max_workspace': '1', 'cudnn_conv1d_pad_to_nc1d': '0', 'tunable_op_enable': '0', 'tunable_op_tuning_enable': '0', 'enable_skip_layer_norm_strict_mode': '0'}, 'CPUExecutionProvider': {}}
Traceback (most recent call last):
  File "F:\ML\facefusion\facefusion\processors\frame\core.py", line 31, in load_frame_processor_module
    frame_processor_module = importlib.import_module('facefusion.processors.frame.modules.' + frame_processor)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ML\facefusion\facefusion\processors\frame\modules\face_enhancer.py", line 4, in <module>
    from gfpgan.utils import GFPGANer
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gfpgan\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gfpgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
ModuleNotFoundError: No module named 'basicsr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\ML\facefusion\facefusion\uis\components\processors.py", line 34, in update_frame_processors
    frame_processor_module = load_frame_processor_module(frame_processor)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ML\facefusion\facefusion\processors\frame\core.py", line 36, in load_frame_processor_module
    sys.exit(wording.get('frame_processor_not_loaded').format(frame_processor = frame_processor))
SystemExit: Frame processor face_enhancer could not be loaded
inswapper-shape: [1, 3, 128, 128]
Traceback (most recent call last):
  File "F:\ML\facefusion\facefusion\processors\frame\core.py", line 31, in load_frame_processor_module
    frame_processor_module = importlib.import_module('facefusion.processors.frame.modules.' + frame_processor)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ML\facefusion\facefusion\processors\frame\modules\face_enhancer.py", line 4, in <module>
    from gfpgan.utils import GFPGANer
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gfpgan\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gfpgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
ModuleNotFoundError: No module named 'basicsr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lodhi\miniconda3\envs\facefusion\Lib\site-packages\gradio\utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\ML\facefusion\facefusion\uis\components\preview.py", line 83, in update
    preview_frame = extract_preview_frame(target_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ML\facefusion\facefusion\uis\components\preview.py", line 105, in extract_preview_frame
    frame_processor_module = load_frame_processor_module(frame_processor)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ML\facefusion\facefusion\processors\frame\core.py", line 36, in load_frame_processor_module
    sys.exit(wording.get('frame_processor_not_loaded').format(frame_processor = frame_processor))
SystemExit: Frame processor face_enhancer could not be loaded

### Description
**I am getting this error when I try pressing face_enhancer and frame_enhancer**

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
