### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not Audio

### ISSUE THREAD

**Issue by heiheiheibj** [facefusion/facefusion#447]
Error after selecting a JPG file for uploading

![image](https://github.com/facefusion/facefusion/assets/6910198/d610aa54-33a8-47f2-968c-94813128729a)

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\blocks.py", line 1341, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\components\audio.py", line 356, in postprocess
    file_path = self.make_temp_copy_if_needed(y)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\components\base.py", line 227, in make_temp_copy_if_needed
    temp_dir = self.hash_file(file_path)
  File "D:\ProgramData\Anaconda3\envs\roop\lib\site-packages\gradio\components\base.py", line 191, in hash_file
    with open(file_path, "rb") as f:
TypeError: expected str, bytes or os.PathLike object, not Audio

thx..

**Comment by henryruhs** [comment]
Please open a #help thread on our [Discord](https://join.facefusion.io) server with the source and target files.
