### ISSUE TITLE
FaceFusion tab is not appearing in Auto1111 [No module named 'realesrgan']

### ISSUE THREAD

**Issue by nitinmukesh** [facefusion/facefusion#454]
This is the error that is appearing

**version: [v1.8.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bef51aed032c0aaa5cfd80445bc4cf0d85b408b5)  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2**

```
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.8.0
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Faceswaplab : Use GPU requirements
Checking faceswaplab requirements
0.005879700001969468
Launching Web UI with arguments:
2024-03-25 00:17:36.368378: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\stable-diffusion-webui\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

No module 'xformers'. Proceeding without it.
[-] ADetailer initialized. version: 24.3.2, num models: 10
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 7, in <module>
        from facefusion.processors.frame.modules import face_enhancer, face_swapper, frame_enhancer
      File "C:\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\processors\frame\modules\frame_enhancer.py", line 6, in <module>
        from realesrgan import RealESRGANer
    ModuleNotFoundError: No module named 'realesrgan'

---
Loading weights [879db523c3] from C:\stable-diffusion-webui\models\Stable-diffusion\dreamshaper_8.safetensors
Creating model from config: C:\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 1.8s (create model: 0.2s, apply weights to model: 1.3s, calculate empty prompt: 0.1s).
C:\stable-diffusion-webui\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by henryruhs** [comment]
We are not the author of that extension.

**Comment by nitinmukesh** [comment]
But the issue is reported for FaceFusion

```
*** Error loading script: facefusion_ui.py
    Traceback (most recent call last):
      File "C:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion-webui\extensions\sd-webui-facefusion\scripts\facefusion_ui.py", line 7, in <module>
        from facefusion.processors.frame.modules import face_enhancer, face_swapper, frame_enhancer
      File "C:\stable-diffusion-webui\extensions\sd-webui-facefusion\facefusion\processors\frame\modules\frame_enhancer.py", line 6, in <module>
        from realesrgan import RealESRGANer
    ModuleNotFoundError: No module named 'realesrgan'
```
