### ISSUE TITLE
Cannot run lip_syncer

### ISSUE THREAD

**Issue by benjaminben** [facefusion/facefusion#478]
Hi there, I'm seeing the following error whenever I attempt to run a lip sync process. The error appears to be on the audio processing side, I've tried various codecs (aac / mp3 / wav) in both stereo and mono, but the error is the same every time. The error is also the same whether running cuda or cpu.

Platform = Windows 10
NVCC = 11.8
Faceswapper = 2.5.0
Python = 3.10.14
numpy = 1.26.4 (installed all dependencies in fresh conda env per documentation)

I don't have experience with earlier versions of Faceswapper so please let me know if there's any other configuration I can test, thank you!

```
[FACEFUSION.CORE] Extracting frames with a resolution of 360x640 and 30 frames per second
[FACEFUSION.PROCESSORS.FRAME.MODULES.LIP_SYNCER] Processing
Processing:   0%| | 0/900 [00:00<?, ?frame/s, execution_providers=['cuda'], execution_thread_count=4, execution_queue_c
Traceback (most recent call last):
  File "~\anaconda3\envs\facefusion\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "~\anaconda3\envs\facefusion\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "~\anaconda3\envs\facefusion\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "~\anaconda3\envs\facefusion\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "~\anaconda3\envs\facefusion\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "~\anaconda3\envs\facefusion\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "~\anaconda3\envs\facefusion\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "~\anaconda3\envs\facefusion\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "D:\Software\facefusion\facefusion\uis\components\output.py", line 70, in process
    conditional_process()
  File "D:\Software\facefusion\facefusion\core.py", line 244, in conditional_process
    process_video(start_time)
  File "D:\Software\facefusion\facefusion\core.py", line 347, in process_video
    frame_processor_module.process_video(facefusion.globals.source_paths, temp_frame_paths)
  File "D:\Software\facefusion\facefusion\processors\frame\modules\lip_syncer.py", line 256, in process_video
    frame_processors.multi_process_frames(source_paths, temp_frame_paths, process_frames)
  File "D:\Software\facefusion\facefusion\processors\frame\core.py", line 87, in multi_process_frames
    future_done.result()
  File "~\anaconda3\envs\facefusion\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "~\anaconda3\envs\facefusion\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "~\anaconda3\envs\facefusion\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Software\facefusion\facefusion\processors\frame\modules\lip_syncer.py", line 228, in process_frames
    source_audio_frame = get_voice_frame(source_audio_path, temp_video_fps, frame_number)
  File "D:\Software\facefusion\facefusion\audio.py", line 63, in get_voice_frame
    voice_frames = read_static_voice(audio_path, fps)
  File "D:\Software\facefusion\facefusion\audio.py", line 33, in read_static_voice
    return read_voice(audio_path, fps)
  File "D:\Software\facefusion\facefusion\audio.py", line 45, in read_voice
    audio = batch_extract_voice(audio, chunk_size, step_size)
  File "D:\Software\facefusion\facefusion\voice_extractor.py", line 64, in batch_extract_voice
    temp_audio[start:end, ...] += extract_voice(audio[start:end, ...])
  File "D:\Software\facefusion\facefusion\voice_extractor.py", line 74, in extract_voice
    temp_audio_chunk, pad_size = prepare_audio_chunk(temp_audio_chunk.T, chunk_size, trim_size)
  File "D:\Software\facefusion\facefusion\voice_extractor.py", line 97, in prepare_audio_chunk
    temp_audio_chunk = numpy.concatenate(temp_audio_chunks, axis = 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 261120 and the array at index 1 has size 7680
```

**Comment by henryruhs** [comment]
Can you reach out via Discord, so I can get the files and debug it?

**Comment by benjaminben** [comment]
Hey closing this issue as I was able to get past the error by reducing my audio file from 18 seconds to 10 seconds long. Same encoding settings but shorter file worked! Is there a documented duration limit for lip_syncer?

**Comment by henryruhs** [comment]
any duration should work, so this is a bug that needs to be addressed.

can you please share the source audio and target video?

**Comment by benjaminben** [comment]
Sure thing! Will share on discord, thanks so much

**Comment by henryruhs** [comment]
open a workshop thread... thanks

**Comment by xpluscal** [comment]
any update on this?

**Comment by benjaminben** [comment]
@xpluscal worked for me after updating to the latest build

**Comment by xpluscal** [comment]
2.5.2 that is?

**Comment by benjaminben** [comment]
I'm still running 2.5.0, @henryruhs pushed a hotfix which resolved this issue shortly after reporting, but the fix presumably exists in the latest version?
