### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by Oooooooooooooooooooooooooooops** [facefusion/facefusion#484]
python3 run.py --output-image-quality 100 --skip-download --output-video-quality 100 --execution-providers cuda --face-selector-mode many --execution-thread-count 32 --execution-queue-count 16 --frame-processors face_swapper --headless --output-video-encoder h264_nvenc --face-swapper-model inswapper_128 -s "1.jpg" -t "2.mp4" -o "/home/spawn/facefusion/spawn4090.mp4"
Analysing:  54%|================================================================================================                                                                                    | 750/1392 [00:02<00:02, 255.67frame/s, rate=0]
Traceback (most recent call last):
  File "/home/spawn/facefusion/run.py", line 6, in <module>
    core.cli()
  File "/home/spawn/facefusion/facefusion/core.py", line 109, in cli
    run(program)
  File "/home/spawn/facefusion/facefusion/core.py", line 204, in run
    conditional_process()
  File "/home/spawn/facefusion/facefusion/core.py", line 246, in conditional_process
    process_video(start_time)
  File "/home/spawn/facefusion/facefusion/core.py", line 324, in process_video
    if analyse_video(facefusion.globals.target_path, facefusion.globals.trim_frame_start, facefusion.globals.trim_frame_end):
  File "/home/spawn/facefusion/facefusion/content_analyser.py", line 107, in analyse_video
    if analyse_frame(frame):
  File "/home/spawn/facefusion/facefusion/content_analyser.py", line 74, in analyse_frame
    vision_frame = prepare_frame(vision_frame)
  File "/home/spawn/facefusion/facefusion/content_analyser.py", line 83, in prepare_frame
    vision_frame = cv2.resize(vision_frame, (224, 224)).astype(numpy.float32)
cv2.error: OpenCV(4.8.1) /io/opencv/modules/imgproc/src/resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by henryruhs** [comment]
Remove special characters from files and paths.
