### ISSUE TITLE
do you have specific version for ffmpeg/opencv for pytorch2.1+cuda118

### ISSUE THREAD

**Issue by qingyuan18** [facefusion/facefusion#515]
there is too many incompatible issues when installing on pytorch2.1+cuda118 docker images:

opencv incompatiable issue: 
File "/opt/program/facefusion/face_analyser.py", line 3, in <module>    import cv2  File "/opt/conda/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>    bootstrap()  File "/opt/conda/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap    native_module = importlib.import_module("cv2")  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module    return _bootstrap._gcd_import(name[level:], package, level) | Traceback (most recent call last): File "/opt/conda/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker worker.init_process() File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi() File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi = self.app.wsgi() File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp() File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri) File "/opt/conda/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app mod = importlib.import_module(module) File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1050, in _gcd_import File "<frozen importlib._bootstrap>", line 1027, in _find_and_load File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 688, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "/opt/program/wsgi.py", line 1, in <module> import predictor as myapp File "/opt/program/predictor.py", line 13, in <module> from facefusion import core File "/opt/program/facefusion/core.py", line 17, in <module> from facefusion.face_analyser import get_one_face File "/opt/program/facefusion/face_analyser.py", line 3, in <module> import cv2 File "/opt/conda/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module> bootstrap() File "/opt/conda/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap native_module = importlib.import_module("cv2") File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level)
-- | --
  | 2024-04-27T03:52:11.112ZImportError: libGL.so.1: cannot open shared object file: No such file or directory

ffmpeg incompatiable issue: 
ffmpeg -hide_banner -loglevel error -hwaccel auto -r 25.0 -i /tmp/facefusion/test/%04d.jpg -c:v libx264 -crf 10 -pix_fmt yuv420p -colorspace bt709 -y /tmp/facefusion/test/temp.mp4
Error: fatal, no -crf options 
Error:fatal, no libx264 encoder

can you provide clear version specific for pytorch2.1+cuda118 so that we can continue the installation? 

many thanks!

**Comment by henryruhs** [comment]
First of all you opened this issue in the wrong repository.

I don't plan to investigate that.

**Comment by qingyuan18** [comment]
First of all , if this repo project are using 3rd party oss frameworks/models such as ffmpeg/opencv/cuda...etc, it should be a good habbit to give out clear guidance for installation's dependancy

I have already fixed the compaitable issue in my env, it should use ffmpeg 4.3+ as well as cu118+pytorch 2.1 , opencv 4.3+ (opencv-python-headless better) , which is applicable for facefusion 

you don't need to investigate on it , just kind remind for a perfect opensource repo should do as most of us think

**Comment by henryruhs** [comment]
in a perfect world you would have opened a pull request rather that opening an issue. as you can see, we are not living in a perfect world.
