### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by zachysaur** [facefusion/facefusion#545]
(venv) (base) D:\New folder (3)\facefusion-unlocked-master>python run.py
Traceback (most recent call last):
  File "D:\New folder (3)\facefusion-unlocked-master\run.py", line 6, in <module>
    core.cli()
  File "D:\New folder (3)\facefusion-unlocked-master\facefusion\core.py", line 108, in cli
    run(program)
  File "D:\New folder (3)\facefusion-unlocked-master\facefusion\core.py", line 223, in run
    ui.launch()
  File "D:\New folder (3)\facefusion-unlocked-master\facefusion\uis\core.py", line 90, in launch
    ui_layout_module.run(ui)
  File "D:\New folder (3)\facefusion-unlocked-master\facefusion\uis\layouts\default.py", line 80, in run
    ui.queue(concurrency_count = concurrency_count).launch(show_api = False, quiet = True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\New folder (3)\facefusion-unlocked-master\venv\Lib\site-packages\gradio\blocks.py", line 2012, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

(venv) (base) D:\New folder (3)\facefusion-unlocked-master>

**Comment by henryruhs** [comment]
you've earned your ban for having the nerve to ask for support here (facefusion-unlocked)
