### ISSUE TITLE
A module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.0

### ISSUE THREAD

**Issue by Lustwaffel** [facefusion/facefusion#634]
I keep running into a numpy issue when trying to install both using the windows installer AND the manual approach.
This is the only ai tool that has this issue at the moment. Does anyone know what I can do here?
I have other tools which I do not want to compromise(not even want the risk) so downgrading something from a 2.0 to a 1.0 is not something I am willing to do. 
#
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\FaceFusion\run.py", line 3, in <module>
    from facefusion import core
  File "C:\FaceFusion\facefusion\core.py", line 10, in <module>
    import onnxruntime
  File "C:\Users\Nuffsaid\AppData\Local\Programs\Miniconda3\envs\facefusion\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Nuffsaid\AppData\Local\Programs\Miniconda3\envs\facefusion\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "C:\FaceFusion\run.py", line 3, in <module>
    from facefusion import core
  File "C:\FaceFusion\facefusion\core.py", line 10, in <module>
    import onnxruntime
  File "C:\Users\Nuffsaid\AppData\Local\Programs\Miniconda3\envs\facefusion\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\Nuffsaid\AppData\Local\Programs\Miniconda3\envs\facefusion\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Nuffsaid\AppData\Local\Programs\Miniconda3\envs\facefusion\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

**Comment by henryruhs** [comment]
Use FF 2.6.1
