### ISSUE TITLE
It failed with an error

### ISSUE THREAD

**Issue by evgebrtwjhr** [facefusion/facefusion#65]
It fails with an error in preview it works but when I click render it fails with the following error

inswapper-shape: [1, 3, 128, 128]
100%|███████████████████████████████████████████████████████████████████████████▉| 12038/12040 [06:10<00:00, 26.09it/s]Traceback (most recent call last):
  File "C:\Users\Z5050\miniconda3\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Z5050\miniconda3\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\Z5050\miniconda3\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Z5050\miniconda3\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Z5050\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Z5050\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Z5050\miniconda3\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Z5050\Desktop\facefusion\facefusion\uis\components\output.py", line 44, in update
    conditional_process()
  File "C:\Users\Z5050\Desktop\facefusion\facefusion\core.py", line 210, in conditional_process
    process_video()
  File "C:\Users\Z5050\Desktop\facefusion\facefusion\core.py", line 151, in process_video
    if predict_video(facefusion.globals.target_path):
  File "C:\Users\Z5050\Desktop\facefusion\facefusion\predictor.py", line 42, in predict_video
    _, probabilities = opennsfw2.predict_video_frames(video_path = target_path, frame_interval = 100)
  File "C:\Users\Z5050\miniconda3\lib\site-packages\opennsfw2\_inference.py", line 178, in predict_video_frames
    cv2.destroyAllWindows()  # pylint: disable=no-member
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1266: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvDestroyAllWindows'

100%|████████████████████████████████████████████████████████████████████████████| 12040/12040 [06:23<00:00, 26.09it/s]

**Comment by henryruhs** [comment]
> Be aware, the installation needs technical skills and is not for beginners. Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.

**Comment by evgebrtwjhr** [comment]
I'm really not a beginner, I checked this error on Google and a variety of tools and I didn't find an answer

**Comment by henryruhs** [comment]
I don't give support via a GitHub, that was the point.
