### ISSUE TITLE
Error cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

### ISSUE THREAD

**Issue by KIROHN616** [facefusion/facefusion#674]
In 1 launch it was the same, then 1 video was able to do and after restarting this error again

List: 
[FACEFUSION.CORE] Извлечение кадров с разрешением 1920x1080 и 29.97002997002997 кадров в секунду
[FACEFUSION.PROCESSORS.FRAME.MODULES.FACE_SWAPPER] Обработка
Обработка:   0%| | 0/2339 [00:00<?, ?frame/s, execution_providers=['cuda', 'cpu'], execution_thread_count=4, execution_queue_count=[ WARN:14@401.571] global loadsave.cpp:248 cv::findDecoder imread_('E:\facefusion-cuda\facefusion\tmp\facefusion\╨▒╤А╨░╤В╨╕╤И╨║╨╕╨╜\0001.png'): can't open/read file: check file path/integrity
[ WARN:15@401.571] global loadsave.cpp:248 cv::findDecoder imread_('E:\facefusion-cuda\facefusion\tmp\facefusion\╨▒╤А╨░╤В╨╕╤И╨║╨╕╨╜\0585.png'): can't open/read file: check file path/integrity
[ WARN:16@401.572] global loadsave.cpp:248 cv::findDecoder imread_('E:\facefusion-cuda\facefusion\tmp\facefusion\╨▒╤А╨░╤В╨╕╤И╨║╨╕╨╜\1169.png'): can't open/read file: check file path/integrity
[ WARN:17@401.575] global loadsave.cpp:248 cv::findDecoder imread_('E:\facefusion-cuda\facefusion\tmp\facefusion\╨▒╤А╨░╤В╨╕╤И╨║╨╕╨╜\1753.png'): can't open/read file: check file path/integrity
[ WARN:14@401.582] global loadsave.cpp:248 cv::findDecoder imread_('E:\facefusion-cuda\facefusion\tmp\facefusion\╨▒╤А╨░╤В╨╕╤И╨║╨╕╨╜\2337.png'): can't open/read file: check file path/integrity
Обработка:   0%| | 0/2339 [00:00<?, ?frame/s, execution_providers=['cuda', 'cpu'], execution_thread_count=4, execution_queue_count=
Traceback (most recent call last):
  File "E:\facefusion-cuda\system\python\lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\facefusion-cuda\system\python\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\facefusion-cuda\system\python\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "E:\facefusion-cuda\system\python\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\facefusion-cuda\system\python\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\facefusion-cuda\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "E:\facefusion-cuda\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "E:\facefusion-cuda\system\python\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "E:\facefusion-cuda\facefusion\facefusion\uis\components\output.py", line 70, in process
    conditional_process()
  File "E:\facefusion-cuda\facefusion\facefusion\core.py", line 269, in conditional_process
    process_video(start_time)
  File "E:\facefusion-cuda\facefusion\facefusion\core.py", line 382, in process_video
    frame_processor_module.process_video(facefusion.globals.source_paths, temp_frame_paths)
  File "E:\facefusion-cuda\facefusion\facefusion\processors\frame\modules\face_swapper.py", line 369, in process_video
    frame_processors.multi_process_frames(source_paths, temp_frame_paths, process_frames)
  File "E:\facefusion-cuda\facefusion\facefusion\processors\frame\core.py", line 87, in multi_process_frames
    future_done.result()
  File "concurrent\futures\_base.py", line 451, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "E:\facefusion-cuda\facefusion\facefusion\processors\frame\modules\face_swapper.py", line 350, in process_frames
    write_image(target_vision_path, output_vision_frame)
  File "E:\facefusion-cuda\facefusion\facefusion\vision.py", line 38, in write_image
    return cv2.imwrite(image_path, vision_frame)
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

**Comment by KIROHN616** [comment]
The problem was in the name of the photo
