### ISSUE TITLE
Problem with calling the inquirer installation

### ISSUE THREAD

**Issue by NeuroDonu** [facefusion/facefusion#682]
Hi!
I found a problem with calling the inquirer installation in file installer.py:
C:\Users\NeuroDonu\Downloads\Telegram Desktop\facefusion-cuda-next\facefusion>python\python.exe install.py
Traceback (most recent call last):
  File "C:\Users\NeuroDonu\Downloads\Telegram Desktop\facefusion-cuda-next\facefusion\install.py", line 8, in <module>
    subprocess.call([ '-m', 'pip', 'install', 'inquirer', '-q' ])
  File "C:\Users\NeuroDonu\Downloads\Telegram Desktop\facefusion-cuda-next\facefusion\python\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\NeuroDonu\Downloads\Telegram Desktop\facefusion-cuda-next\facefusion\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\NeuroDonu\Downloads\Telegram Desktop\facefusion-cuda-next\facefusion\python\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Unable to find the specified file

and it was solved with this little change:
import sys
python_executable = sys.executable
subprocess.call([python_executable, '-m', 'pip', 'install', 'inquirer', '-q' ])

**Comment by henryruhs** [comment]
That is usually caused by setting up conda with Python 3.12 ... Please join [Discord](https://join.facefusion.io) for help.
