### ISSUE TITLE
OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize' 

### ISSUE THREAD

**Issue by ZeeLyn** [facefusion/facefusion#685]
When using lip_synter, throw an error when you execute Analysing to 52%:

```powershell
(base) PS D:\GitHub\facefusion> python .\run.py                                                  e 162
Running on local URL:  http://127.0.0.1:7860
Analysing:  52%|=================                 | 800/1536 [00:08<00:07, 93.39frame/s, rate=0]
Traceback (most recent call last):
  File "D:\GitHub\facefusion\.venv\lib\site-packages\gradio\queueing.py", line 407, in call_predi0framction                                                                                                 , in _call_co
    output = await route_utils.call_process_api(                                                  erro
  File "D:\GitHub\facefusion\.venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(                                                 l] Noe/s, rate=0]v
  File "D:\GitHub\facefusion\.venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api D:\a    result = await self.call_function(                                                           ::Inpr: (-215:Asse
  File "D:\GitHub\facefusion\.venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(                                                 6framn-zero status
  File "D:\GitHub\facefusion\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync        clude\onnxrun
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\GitHub\facefusion\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in ction
run_sync_in_worker_thread                                                                             e/s, rate=0] 
    return await future
  File "D:\GitHub\facefusion\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in rocessun
    result = context.run(func, *args)                                                                 _api
  File "D:\GitHub\facefusion\.venv\lib\site-packages\gradio\utils.py", line 661, in wrapper           
    response = f(*args, **kwargs)
  File "D:\GitHub\facefusion\facefusion\uis\components\output.py", line 70, in process           on   
    conditional_process()
  File "D:\GitHub\facefusion\facefusion\core.py", line 269, in conditional_process                    
    process_video(start_time)
  File "D:\GitHub\facefusion\facefusion\core.py", line 357, in process_video                     run_s
    if analyse_video(facefusion.globals.target_path, facefusion.globals.trim_frame_start, facefus     ync_in_workerion.globals.trim_frame_end):
  File "D:\GitHub\facefusion\facefusion\content_analyser.py", line 108, in analyse_video         un   
    if analyse_frame(frame):
  File "D:\GitHub\facefusion\facefusion\content_analyser.py", line 73, in analyse_frame
    vision_frame = prepare_frame(vision_frame)
  File "D:\GitHub\facefusion\facefusion\content_analyser.py", line 83, in prepare_frame
    vision_frame = cv2.resize(vision_frame, (224, 224)).astype(numpy.float32)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4152: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```
Positioning output found that the parameter "Vision_frame" passed in this [function](https://github.com/facefusion/facefusion/blob/57016d7c778c70f58fc54c49013d57179874a505/facefusion/content_analyser.py#L82-L86) is None

**Comment by henryruhs** [comment]
Corrupt frame in the video...
