### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed. (please help)

### ISSUE THREAD

**Issue by jambgithub** [facefusion/facefusion#753]
(face) C:\Users\jbl\anaconda3\envs\face\facefusion>python run.py
Traceback (most recent call last):
  File "C:\Users\jbl\anaconda3\envs\face\facefusion\run.py", line 3, in <module>
    from facefusion import core
  File "C:\Users\jbl\anaconda3\envs\face\facefusion\facefusion\core.py", line 8, in <module>
    from facefusion import content_analyser, face_classifier, face_detector, face_landmarker, face_masker, face_recognizer, logger, process_manager, state_manager, voice_extractor, wording
  File "C:\Users\jbl\anaconda3\envs\face\facefusion\facefusion\content_analyser.py", line 7, in <module>
    from facefusion import inference_manager, state_manager, wording
  File "C:\Users\jbl\anaconda3\envs\face\facefusion\facefusion\inference_manager.py", line 5, in <module>
    import onnx
  File "C:\Users\jbl\anaconda3\envs\face\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

**Comment by jambgithub** [comment]
Sorry i have try many time , check the requirement , reinstall the facefusion 3.0.0 , using python 3.10 , python install.py --onnxruntime cuda , pip install requirements.txt , pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 and finally run python facefusion.py run . it works ! , as the GPU C/C++ package of onnxruntime 1.19.2 is for compatible with cuda 12.x and cudnn 9.x and finnaly it work !

**Comment by henryruhs** [comment]
PyTorch is definitely the worst "solution" possible. Remove it from your environment and try this instead.

```
winget install --id=Microsoft.VCRedist.2015+.x86  -e
```
