### ISSUE TITLE
conda windows 11 install error

### ISSUE THREAD

**Issue by senthilnayagam** [facefusion/facefusion#757]
conda windows 11, getting this error 
 (3.0.0) PS C:\Users\senth\facefusion\facefusion-3.0.0> python .\install.py  --onnxruntime cuda

Traceback (most recent call last):
  File "C:\Users\senth\facefusion\facefusion-3.0.0\install.py", line 10, in <module>
    installer.cli()
  File "C:\Users\senth\facefusion\facefusion-3.0.0\facefusion\installer.py", line 33, in cli
    run(program)
  File "C:\Users\senth\facefusion\facefusion-3.0.0\facefusion\installer.py", line 90, in run
    subprocess.call([ shutil.which('conda'), 'env', 'config', 'vars', 'set', 'PATH=' + os.pathsep.join(library_paths) ])
  File "C:\Users\senth\miniconda3\envs\3.0.0\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\senth\miniconda3\envs\3.0.0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\senth\miniconda3\envs\3.0.0\lib\subprocess.py", line 1380, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\senth\miniconda3\envs\3.0.0\lib\subprocess.py", line 563, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\senth\miniconda3\envs\3.0.0\lib\os.py", line 823, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by henryruhs** [comment]
Please join [Discord](https://join.facefusion.io) for help.
