### ISSUE TITLE
(-215:Assertion failed) !_img.empty() in function 'cv::imwrite

### ISSUE THREAD

**Issue by StartHua** [facefusion/facefusion#81]
002] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\Administrator\AppData\Local\Temp\facefusion\涓嬭浇\0001.jpg'): can't open/read file: check file path/integrity
Processing:   0%|                                                                          | 0/7958 [00:00<?, ?frame/s]
Traceback (most recent call last):
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\python\Anaconda\envs\facefusion\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "F:\AI\facefusion-master\facefusion\uis\components\output.py", line 53, in start
    conditional_process()
  File "F:\AI\facefusion-master\facefusion\core.py", line 207, in conditional_process
    process_video()
  File "F:\AI\facefusion-master\facefusion\core.py", line 171, in process_video
    frame_processor_module.process_video(facefusion.globals.source_path, temp_frame_paths)
  File "F:\AI\facefusion-master\facefusion\processors\frame\modules\face_swapper.py", line 100, in process_video
    frame_processors.process_video(source_path, temp_frame_paths, process_frames)
  File "F:\AI\facefusion-master\facefusion\processors\frame\core.py", line 91, in process_video
    multi_process_frame(source_path, frame_paths, process_frames, lambda: update_progress(progress))
  File "F:\AI\facefusion-master\facefusion\processors\frame\core.py", line 69, in multi_process_frame
    future.result()
  File "D:\python\Anaconda\envs\facefusion\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "D:\python\Anaconda\envs\facefusion\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\python\Anaconda\envs\facefusion\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\AI\facefusion-master\facefusion\processors\frame\modules\face_swapper.py", line 85, in process_frames
    cv2.imwrite(temp_frame_path, result_frame)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:787: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'

**Comment by henryruhs** [comment]
That is not a valid bug report.

**Comment by dantecsm** [comment]
视频文件名不要包含中文
