### ISSUE TITLE
Just stops.

### ISSUE THREAD

**Issue by tpcdaz** [facefusion/facefusion#82]
Hey!

I love the software and been having fun with it but there are times when it just wont do anything. 

I tried with a particular video and got this through the command prompt

"Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Koppi\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Koppi\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Koppi/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Koppi/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Koppi/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Koppi/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Koppi/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
1/1 [==============================] - 1s 646ms/step
100%|█████████████████████████████████████████████████████████████████████████████| 5025/5025 [00:17<00:00, 285.24it/s]"

No errors, no issues it goes through the steps, gets to 100% then just does nothing. It works with some videos but not all and not sure why. Any ideas?

**Comment by tpcdaz** [comment]
Nevermind I found out why. The video had a guy in a fake muscle suit that I wanted to change the face too and I think FaceFusion was mistakingly flagging it as NSFW so it skipped the frames. I understand the need to be safe with thing but often these filters can go OTT
