### ISSUE TITLE
How to use CUDA 12.1? Because CUDA 12.1 is already present in my Windows 11, I can't use this project.

### ISSUE THREAD

**Issue by wibur0620** [facefusion/facefusion#89]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[ WARN:0@14.316] global loadsave.cpp:248 cv::findDecoder imread_('C:\Users\绌虹伒\AppData\Local\Temp\gradio\910e86be83c12457001fbbf9a72d1a1d8281f2c0\m 1.png'): can't open/read file: check file path/integrity
2023-09-09 16:34:16.7375527 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-09-09 16:34:16.8897262 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2023-09-09 16:34:17.0701632 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-09-09 16:34:17.2422809 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\uis\components\face_selector.py", line 110, in update_face_reference_position
    gallery_frames = extract_gallery_frames(reference_frame)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\uis\components\face_selector.py", line 126, in extract_gallery_frames
    faces = get_many_faces(reference_frame)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\face_analyser.py", line 41, in get_many_faces
    faces = get_face_analyser().get(frame)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\face_analyser.py", line 18, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name = 'buffalo_l', providers = facefusion.globals.execution_providers)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

Traceback (most recent call last):
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\routes.py", line 523, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\uis\components\preview.py", line 94, in update_preview_image
    conditional_set_face_reference()
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\uis\components\preview.py", line 139, in conditional_set_face_reference
    reference_face = get_one_face(reference_frame, facefusion.globals.reference_face_position)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\face_analyser.py", line 30, in get_one_face
    many_faces = get_many_faces(frame)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\face_analyser.py", line 41, in get_many_faces
    faces = get_face_analyser().get(frame)
  File "D:\AI\AIshipin\FaceFusion\facefusion\facefusion\face_analyser.py", line 18, in get_face_analyser
    FACE_ANALYSER = insightface.app.FaceAnalysis(name = 'buffalo_l', providers = facefusion.globals.execution_providers)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\app\face_analysis.py", line 31, in __init__
    model = model_zoo.get_model(onnx_file, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "D:\AI\AIshipin\FaceFusion\facefusion\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by wibur0620** [comment]
I want to use CUDA 12.1 to run this project.

**Comment by henryruhs** [comment]
> Please do not open platform and installation related issues on GitHub. We have a very helpful [Discord](https://join.facefusion.io/) community that will guide you to install FaceFusion.
